E.
======================================================================
ERROR: test_main (unittest.loader._FailedTest.test_main)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_main
Traceback (most recent call last):
  File "C:\Python312\Lib\unittest\loader.py", line 396, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\unittest\loader.py", line 339, in _get_module_from_name
    __import__(name)
  File "C:\Users\John\Desktop\tailserve\test_main.py", line 3, in <module>
    from main import app
  File "C:\Users\John\Desktop\tailserve\main.py", line 2, in <module>
    @app.get("/")
     ^^^
NameError: name 'app' is not defined


----------------------------------------------------------------------
Ran 2 tests in 0.465s

FAILED (errors=1)
